name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # setiap hari jam 03:00 UTC
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [firefox, webkit]
    env:
      UI_AUTOMATION_BROWSER: ${{ matrix.browser }}
      PARALLEL: 2
      RETRY: 1
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Cucumber tests on ${{ matrix.browser }}
      run: |
        npx cucumber-js ./src/features/*.feature \
          --require-module ts-node/register \
          --require ./src/step-definitions/**/**/*.ts \
          --require ./src/utils/cucumber-timeout.ts \
          -f json:./reports/${{ matrix.browser }}/report.json \
          --format html:./reports/${{ matrix.browser }}/report.html \
          --format progress \
          --parallel $PARALLEL \
          --retry $RETRY \
          --tags "not @ignore"
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Download all reports
      uses: actions/download-artifact@v4
      with:
        path: reports
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
